baseURL = 'https://vpn-sicher.de'
languageCode = 'de-de'
title = 'TarnVPN'
theme = "tarnvpn"
buildfuture = true
#enableGitInfo = true
markup.goldmark.renderer.unsafe = true

[params]
title = "Die sichersten VPN Anbieter"
description = "Sichere VPN Anbieter im unabhängigen Vergleich"
logo = "/assets/tarnkappe.png"

[params.footer]
Logo = "/assets/tarnkappe_black.png"
Copyright = "tarnkappe.info"

[params.footer.col1]
head = "Besuche uns"
[[params.footer.col1.links]]
url = "https://tarnkappe.info"
text = "News"
[[params.footer.col1.links]]
url = "https://tarnkappe.info/forum/"
text = "Forum"
[[params.footer.col1.links]]
url = "https://t.me/tarnkappe"
text = "Telegram Channel"
[[params.footer.col1.links]]
url = "https://matrix.to/#/#chat:tarnkappe.info"
text = "Matrix Channel"

[params.footer.col2]
head = "Folge uns"
[[params.footer.col2.links]]
url = "https://social.tchncs.de/@tarnkappeinfo"
text = "Mastodon"
[[params.footer.col2.links]]
url = "https://twitter.com/tarnkappe_info"
text = "Twitter"
[[params.footer.col2.links]]
url = "https://www.facebook.com/tarnkappe.info/"
text = "Facebook"

[params.footer.col3]
head = "Über uns"

[[params.footer.col3.links]]
url = "https://tarnkappe.info/kontakt"
text = "Kontakt"

[[params.footer.col3.links]]
url = "https://tarnkappe.info/ueber-tarnkappe"
text = "Wer wir sind"

[params.footer.col4]
head = "Impressum"
lines = [
	"Lars Sobiraj",
	"Tarnkappe.info Gewerbebetrieb",
	"c/o Postflex #3386",
	"Emsdettener Str. 10",
	"48268 Greven",
]
